# Assumes firehose_exporter is being used: ./monitor-cf.yml and ./deprecated/use-cf-attic.yml
# loggregatorv2 has no meaning for updated firehose_exporter

- type: replace
  path: /instance_groups/name=firehose/jobs/name=firehose_exporter-attic/properties/firehose_exporter/logging/url?
  value: https://log-stream.((system_domain))

- type: replace
  path: /instance_groups/name=firehose/jobs/name=firehose_exporter-attic/properties/firehose_exporter/logging/use_legacy_firehose?
  value: false
